Use SpanManager as a common mechanism for propagating trace context b…
opentracing-contrib/java-web-servlet-filter pull request #11
Opened 2017-02-28 13:44 UTC by objectiser

…etween different framework integrations

2017-02-28 13:45 UTC, objectiser commented
@pavolloffay Could you review when convenient - not urgent.

2017-03-13 12:47 UTC, pavolloffay requested changes
LGTM,

just some refactoring issues.

2017-03-13 12:47 UTC, pavolloffay commented on opentracing-web-servlet-filter/src/main/java/io/opentracing/contrib/web/servlet/filter/SpanWrapper.java
>      private Span span;
Could you please remove this and use only `managedSpan`?

2017-03-13 12:47 UTC, pavolloffay commented on opentracing-web-servlet-filter/src/main/java/io/opentracing/contrib/web/servlet/filter/SpanWrapper.java
>          if (!wasFinished) {
not related to this but could you please rewrite this to:

`if (finished.compareAndSet(false,true))`

2017-03-13 12:47 UTC, pavolloffay commented on opentracing-web-servlet-filter/src/test/java/io/opentracing/contrib/web/servlet/filter/AbstractJettyTest.java
> +    public static class CurrentSpanServlet extends HttpServlet {
Could you please move this below `LocalSpanServlet` and the same with `        servletContext.addServlet(CurrentSpanServlet.class, "/currentSpan");
`

2017-03-13 12:47 UTC, pavolloffay commented on opentracing-web-servlet-filter/src/test/java/io/opentracing/contrib/web/servlet/filter/AbstractJettyTest.java
> +            response.setStatus(DefaultSpanManager.getInstance().current().getSpan() == null ? 500 : 204);
Could you please add a tag to the current span and assert on that? (so all the tests are conceptually the same).

2017-03-13 16:17 UTC, pavolloffay commented on opentracing-web-servlet-filter/src/test/java/io/opentracing/contrib/web/servlet/filter/TracingFilterTest.java
> +        List<MockSpan> mockSpans = mockTracer.finishedSpans();
One thing, the wait statement is missing before this. It can potentially cause unstable CI.

2017-03-13 16:23 UTC, objectiser commented on opentracing-web-servlet-filter/src/test/java/io/opentracing/contrib/web/servlet/filter/TracingFilterTest.java
> +        List<MockSpan> mockSpans = mockTracer.finishedSpans();
Updated.

2017-03-13 16:32 UTC, pavolloffay approved these changes

2017-03-13 16:33 UTC, merged